Initial import

In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import Scripts.sql_server_connect as sql

ModuleNotFoundError: No module named 'Scripts.sql_server_connect'

Part 1: Category Sales Analysis for period 06.2017-06.2018
Targeted Category: Health And Beauty

In [ ]:
# Connecting to MSSQL Server database
database = "OlistDB"
server = r"localhost\SQLEXPRESS"
engine = sql.mssql_engine(server,database)

In [ ]:


print("Data returned from Microsoft SQL Server:")
df_category_revenue = sql.load_sql_to_df(r"Queries\SQL Business queries\SQL Revenue by Category.sql", 
                                     engine.connect())
df_category_revenue.head(5)

Data returned from Microsoft SQL Server:

,category_name,category_count,gross_merchandise_value,gross_order_value,gross_freight_cost
0,health_beauty\r,6909,1005736.20,878067.06,127669.14
1,watches_gifts\r,4576,969955.84,894607.20,75348.64
2,bed_bath_table\r,8559,961167.01,806385.45,154781.56
3,sports_leisure\r,6562,866209.46,740550.53,125658.93
4,computers_accessories\r,6056,814724.85,700504.76,114220.09

In [ ]:
df_category_revenue['category_name'] = df_category_revenue['category_name'].str.strip("\r")
df_category_revenue.head(5)

In [ ]:
df_top_revenue = df_category_revenue.nlargest(10,["gross_merchandise_value"])
df_top_revenue

,category_name,category_count,gross_merchandise_value,gross_order_value,gross_freight_cost
0,health_beauty,6909,1005736.20,878067.06,127669.14
1,watches_gifts,4576,969955.84,894607.20,75348.64
2,bed_bath_table,8559,961167.01,806385.45,154781.56
3,sports_leisure,6562,866209.46,740550.53,125658.93
4,computers_accessories,6056,814724.85,700504.76,114220.09
5,furniture_decor,6018,644706.70,523054.75,121651.95
6,cool_stuff,2898,542669.14,478932.31,63736.83
7,housewares,4839,532860.54,432118.00,100742.54
8,auto,3032,492161.30,426236.71,65924.59
9,toys,3169,431271.51,371754.35,59517.16